### ISSUE TITLE
Scotchbox, vagrant and wordpress localhost error

### ISSUE THREAD

**Issue by Cyra25** [flurinduerst/WPDistillery#100]
I'm using scotch box together with vagrant to make a wordpress in localhost environment. When i go to 192.168.33.10, it got redirected to the wpdistillery.vm. But it works when i go to administrator page. Help me solve it please.

Solved:
Solution: reinstall everything (vagrant, scotchbox and virtual machine)

**Comment by flurinduerst** [comment]
Would you mind sharing the cause and solution on this with other users? :)
