### ISSUE TITLE
Setup.sh errors

### ISSUE THREAD

**Issue by rowboat85** [flurinduerst/WPDistillery#16]
Hi I am running a window 8.1 machine.

I am getting this error on step 4. cd ../../var/www/ && bash setup.sh

setup.sh: line 9: $'\r': command not found
setup.sh: line 12: syntax error near unexpected token `$'{\r''
'etup.sh: line 12:`function continue_error {

**Comment by flurinduerst** [comment]
Hi rowboat85
Thanks for drawing attention to this issue.

Text files created on Unix/Linux machines have different line endings than files created on DOS/Windows. DOS uses carriage return and line feed `\r\n` as a line ending. Unix uses just line feed `\n`. 

EDIT: Please use dos2unix as stated by ShaneSimpson two comments below this one.

**Comment by flurinduerst** [comment]
@rowboat85 did it work for you? If so, we can close the issue :)

**Comment by vsmith72** [comment]
I'm getting the same error. I used the code in the gist and get the same error message.
I run windows 10.

**Comment by ShaneShipston** [comment]
I solved my issue on Windows by running the following:

```
vagrant up
vagrant ssh
sudo apt-get install -y dos2unix
cd /var/www
dos2unix config.yml
dos2unix install.sh
```

Then finally run `bash setup.sh`

**Comment by rowboat85** [comment]
Hi sorry for the delayed response, I am on a tight deadline with a project and using MAC now with no issues. May get a chance in a couple of weeks to have a look on PC. Sry thx.

**Comment by Rocknpools** [comment]
hi i got this error running setup.sh. Someone can help me?


========== WPDISTILLERY START ==========

[=== INSTALL WORDPRESS ===]
»»» downloading WordPress...
Downloading WordPress 4.6.1 (en_US)...
md5 hash verified: ca0b978fd702eac033830ca2d0784b79
Success: WordPress downloaded.
»»» creating wp-config...
Success: Generated 'wp-config.php' file.
»»» installing wordpress...
/home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/smtp.rb:541:in `initialize': Connection refused - connect(2) for "127.0.0.1" port 1025 (Errno::ECONNREFUSED)
	from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/smtp.rb:541:in `open'
	from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/smtp.rb:541:in `tcp_socket'
	from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/smtp.rb:551:in `block in do_start'
	from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
	from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/timeout.rb:99:in `call'
	from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/timeout.rb:99:in `timeout'
	from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/smtp.rb:550:in `do_start'
	from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/smtp.rb:520:in `start'
	from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'
	from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/mail-2.6.3/lib/mail/message.rb:2141:in `do_delivery'
	from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/mail-2.6.3/lib/mail/message.rb:238:in `deliver'
	from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/mailcatcher-0.6.1/bin/catchmail:71:in `<top (required)>'
	from /home/vagrant/.rbenv/versions/2.2.2/bin/catchmail:23:in `load'
	from /home/vagrant/.rbenv/versions/2.2.2/bin/catchmail:23:in `<main>'
Success: WordPress installed successfully.

**Comment by ajs476** [comment]
@ShaneShipston I was also getting the error after using the "DOS" friendly setup.sh file, and tried your method with dos2unix.  This is what I get.

```
vagrant@scotchbox:/var/www$ clear
vagrant@scotchbox:/var/www$ bash setup.sh
========== WPDISTILLERY START ==========

mkdir: cannot create directory ‘(public)\r’: Protocol error
Do you want to continue anyway? (y/n) y
»»» continuing WPDistillery setup...
... creating WP Folder (public)
: No such file or directorylic)
Do you want to continue anyway? (y/n) y
»»» continuing WPDistillery setup...
setup.sh: line 72: $'(true)\r': command not found
>>> skipping WordPress installation...
setup.sh: line 84: $'(true)\r': command not found
>>> skipping settings...
setup.sh: line 116: $'(true)\r': command not found
>>> skipping theme installation...
setup.sh: line 144: $'(true)\r': command not found
>>> skipping Cleanup...
setup.sh: line 173: $'(true)\r': command not found
>>> skipping Plugin installation...
»»» checking wp cli version
Success: WP-CLI is at the latest version.
========== WPDISTILLERY FINISHED ==========
vagrant@scotchbox:/var/www$
```

It doesn't actually create anything since there are obviously errors. Anyone have any solutions for windows users that I might try?

**Comment by ShaneShipston** [comment]
It doesn't look like the dos2unix command was successful.

**Comment by ajs476** [comment]
@ShaneShipston In your original post you said to run "dos2unix install.sh",  my script is named 'setup.sh', so I'm assuming that is what I would need to run dos2unix on.

Here is what I did: 

```
vagrant@scotchbox:/var/www$ dos2unix setup.sh
dos2unix: converting file setup.sh to Unix format ...
vagrant@scotchbox:/var/www$ bash setup.sh
========== WPDISTILLERY START ==========

mkdir: cannot create directory ‘(public)\r’: Protocol error
Do you want to continue anyway? (y/n)
```

It seems as though dos2unix is not properly working, although I'm not sure. Any other ideas?

EDIT: I did a not so smart thing, I used dos2unix on the "DOS" version of the setup.sh, so It didn't work as expected...  I went and got the original unix script, ran dos2unix, and it seems to be working just fine.. Thanks!

**Comment by flurinduerst** [comment]
@ShaneShipston thanks a lot for writing down your solution. I will add it to the Docs.

**Comment by cdrrazan** [comment]
I am running scotch box on Ubuntu 16.10 and getting this error when running 
bash setup.sh

»»» downloading WordPress...
/usr/local/bin/wp: line 1: syntax error near unexpected token `newline'
/usr/local/bin/wp: line 1: `<?xml version="1.0" encoding="UTF-8"?>'

Any linux user here?

**Comment by darek** [comment]
git config --global core.autocrlf false

clone again repository and You should be good
