### ISSUE TITLE
PHP Fatal error:  Call to undefined function apply_filters() in /var/www/public/wp-includes/load.php on line 317

### ISSUE THREAD

**Issue by sumnermic** [flurinduerst/WPDistillery#17]
Hello,

I've performed the following to receive the error:
- Follow install Scotchbox with WPDistillery, following all the defaults
- `vagrant ssh`
- \- `bash setup.sh` (WordPress 4.6 then installs)
  Then I am stopped by the error titled above.
### Terminal log:

```
vagrant@scotchbox:/var/www$ bash setup.sh
========== WPDISTILLERY START ==========

[=== INSTALL WORDPRESS ===]
»»» downloading WordPress...
Downloading WordPress 4.6 (en_US)...
Using cached file '/home/vagrant/.wp-cli/cache/core/wordpress-4.6-en_US.tar.gz'...
Success: WordPress downloaded.
»»» creating wp-config...
Success: Generated wp-config.php file.
»»» installing wordpress...
PHP Fatal error:  Call to undefined function apply_filters() in /var/www/public/wp-includes/load.php on line 317
Do you want to continue anyway? (y/n) y
»»» continuing WPDistillery setup...
»»» configure settings...
» timezone:
PHP Fatal error:  Call to undefined function apply_filters() in /var/www/public/wp-includes/load.php on line 317
Do you want to continue anyway? (y/n)

»»» aborting WPDistillery setup!
```

Could this be due to WordPress 4.6?

Kind regards,

sumnermic

**Comment by scherii** [comment]
`wp cli update` should do the trick. [The latest version is 0.24.1](https://github.com/wp-cli/wp-cli/releases).

See this related issue: https://github.com/roots/trellis/issues/639

**Comment by drawcard** [comment]
For anyone trying to run this command in Scotch Box, you need to force it like so:

`sudo wp cli update --allow-root`
