### ISSUE TITLE
Permission denied (publickey). fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by muygalan** [flurinduerst/WPDistillery#18]
I have been following the instructions on the [SCOTCH BOX 2.5](https://box.scotch.io/) website. 
- I have installed Vagrant
- I have installed VirtualBox
- I have cloned the Scotch Box GitHub Repository and successfully ran Vagrant

Where I'm running into trouble is setting up WPDistillery via my Windows command prompt.

I typed the following line: 
`git clone git@github.com:flurinduerst/WPDistillery.git`

and I receive the following message:

`Cloning into 'WPDistillery'...`
`Permission denied (publickey).`
`fatal: Could not read from remote repository.`

`Please make sure you have the correct access rights`
`and the repository exists.`

Any thoughts as to what is happening and how it can be corrected?

**Comment by ShaneShipston** [comment]
Try `git clone https://github.com/flurinduerst/WPDistillery.git` instead

**Comment by flurinduerst** [comment]
Using the https clone command (as in the answer of @ShaneShipston) should fix it. Will update this in the Docs. Thanks.
