### ISSUE TITLE
Windows install instructions unclear - dos2unix

### ISSUE THREAD

**Issue by seanhak** [flurinduerst/WPDistillery#21]
If you're a moron like me...
I tried to run dos2unix install.sh a few times before realizing it's setup.sh...

**Comment by ShaneShipston** [comment]
That was my bad. I forgot I had renamed the file in my set up.

**Comment by flurinduerst** [comment]
My bad for applying it. Thanks for the info @seanhak! Merged your pull request (ae115ba150ec34d53036f4c53c96c24693af7bba) @ShaneShipston
