### ISSUE TITLE
Changing the Public Folder Name without having to run through setup again

### ISSUE THREAD

**Issue by rowboat85** [flurinduerst/WPDistillery#24]
Hi I have setup my box and just wondering if I change the name of the public folder would this crash the box? Or where would change all references to the 'public' folder without having to run through the setup all over again?

**Comment by rowboat85** [comment]
Sorry it was prob a dumb question.
I figured it out changed the document root in /etc/apache2/000-default.conf and scotchbox.local.conf.

Thanks

**Comment by flurinduerst** [comment]
No problem. For detailed instructions on how to change the public folder see https://github.com/scotch-io/scotch-box/issues/14

Note: This issue is related to [scotchbox](https://github.com/scotch-io/scotch-box), not WPDistillery itself :)
