### ISSUE TITLE
Intermittent cURL errors

### ISSUE THREAD

**Issue by peterdalydickson** [flurinduerst/WPDistillery#33]
I keep experiencing `Warning: Download failed. "cURL error 56: Recv failure: Connection reset by peer"` when installing 'private' plugins, but not on all...

<img width="726" alt="nathans-imac_local" src="https://cloud.githubusercontent.com/assets/17453188/20573279/f190034e-b1a6-11e6-88f4-0043cf3a106e.png">

As it's inconsistent, I'm not really sure where/how to troubleshoot.

Any ideas?

**Comment by flurinduerst** [comment]
This might not be an issue with WPDistillery. It could be an issue with a firewall or a service that was temporarily unavailable. Please check [this stackoverflow thread](http://stackoverflow.com/questions/10285700/curl-error-recv-failure-connection-reset-by-peer-php-curl) or try googling the error message for further information.
