### ISSUE TITLE
Plugin that requires ioncube fails to activate

### ISSUE THREAD

**Issue by peterdalydickson** [flurinduerst/WPDistillery#34]
One of the plugins I'm installing with WPDistillery requires ionCube Loader.

The first time I got an error during `bash setup.sh`, I added the appropriate loader via vagrant provision.

However, despite the fact ioncube loader is now present, and apache is restarted at the end of vagrant provisioning, I still get this error...

<img width="713" alt="hub2-wp_ _vagrant_hub2___var_www_files_ _ssh_ _vagrant_ssh_ _101x54_and_new_issue_ _flurinduerst_wpdistillery" src="https://cloud.githubusercontent.com/assets/17453188/20596730/c32ae6ae-b237-11e6-991f-841aa963d398.png">

**Comment by flurinduerst** [comment]
Did you make sure that ioncube was installed correctly by creating/executing a testfile as stated on https://www.digitalocean.com/community/tutorials/how-to-install-ioncube-loader-on-ubuntu-12-04? If so, have you been able to use ioncube with WP-CLI before?

**Comment by peterdalydickson** [comment]
Thanks for response.

ioncube is definitely installed because when the provisioning finishes, I can login to wp-admin and activate the ‘problem’ plugin with no errors.



---
      Peter Daly-Dickson


On 6 December 2016 at 03:44:05, Flurin Dürst (notifications@github.com) wrote:

Did you make sure that ioncube was installed correctly by creating/executing a testfile as stated on https://www.digitalocean.com/community/tutorials/how-to-install-ioncube-loader-on-ubuntu-12-04?

**Comment by flurinduerst** [comment]
Have you been able to use ioncube with WP-CLI before?

**Comment by peterdalydickson** [comment]
WPDistillery is my first experience with wp-cli!

(And a very good first experience too, I might add)



---
      Peter Daly-Dickson


On 6 December 2016 at 05:16:01, Flurin Dürst (notifications@github.com) wrote:

Have you been able to use ioncube with WP-CLI before?

**Comment by flurinduerst** [comment]
That's nice to hear :) To make sure this is a WPDistillery issue, and not related to WP-CLI or Scotchbox, please try using ioncube with WP-CLI outside WPDistillery/Scotchbox.
