### ISSUE TITLE
Error in Jetpack plugin settings menu

### ISSUE THREAD

**Issue by johnpitchko** [flurinduerst/WPDistillery#40]
Running WP 4.7.1 and Jetpack 4.5 on latest version of WPDistillery. When I open the Jetpack settings on my localhost, I receive the following error:
`Warning: stripos() expects parameter 1 to be string, array given in /var/www/public/wp-includes/formatting.php on line 3774`

Using stock Twentysixteen theme. All plugins deleted except for Jetpack.

Confirmed on two separate installs of WPDistillery.

Can anyone else replicate this error?

**Comment by johnpitchko** [comment]
And I receive this error when I try to activate modules in Jetpack:
`Custom Content Types failed to activate. SyntaxError: Unexpected token < in JSON at position 0`

**Comment by flurinduerst** [comment]
Hi @johnpitchko,
I was able to replicate 
```Warning: stripos() expects parameter 1 to be string, array given in /var/www/public/wp-includes/formatting.php on line 3774```.

I think this is an Jetpack related error as everything else seems to work fine. Maybe we need to change a php-setting on the local machine. Do you also get this error on the live site using WordPress 4.7.1?

**Comment by johnpitchko** [comment]
Hello @flurinduerst no issues on my live site (WP 4.7.1 using Jetpack 4.5). Agree its likely a php-setting or something. Will help you debug.

**Comment by johnpitchko** [comment]
Ok tried with a brand new install using the latest version of WPDistillery. The initial issue is gone (the stringpos() warning), however I am still encountering the `Custom Content Types failed to activate. SyntaxError: Unexpected token < in JSON at position 0` when trying to activate the Custom Content Types module in Jetpack. If I enable the setting and refresh the page, it all seems the setting shows as being active.

**Comment by flurinduerst** [comment]
Issue is caused by jetpack itself on some server-settings. https://wordpress.org/support/topic/syntaxerror-unexpected-token-in-json-at-position-0/

Thanks for reporting @johnpitchko :)
