### ISSUE TITLE
Config File Contains Syntax Errors

### ISSUE THREAD

**Issue by XedinUnknown** [flurinduerst/WPDistillery#46]
The [`config.yml`](https://github.com/flurinduerst/WPDistillery/blob/35faf6a66c10b94157222f80f683809feb1640e1/wpdistillery/config.yml) file contains a syntax error. Both NetBeans 8.1 and [yamllint.com](http://www.yamllint.com/) report the same error:
> (\<unknown\>): mapping values are not allowed in this context at line 56 column 19

This is probably due to the fact that the line is indented. Removing indentation causes the parser to continue and to find another error:
> (\<unknown\>): mapping values are not allowed in this context at line 107 column 12

Cause of this error, and the errors on the 3 lines following it, are the same as the first one. I understand that the indentation is probably there to group related values; however, in YAML, indentation has syntactic significance. Besides not displaying correctly in editors with syntax highlighting, I imagine this also makes standards-compliant parsers unable to parse the configuration.

**Comment by flurinduerst** [comment]
Thanks for checking validation. Fixed this in 4a86057b8f197d0660f53921a277bb19638c0233. yamllint.com returns no errors now.

**Comment by XedinUnknown** [comment]
Commented on that commit. Please see, @flurinduerst.
