### ISSUE TITLE
How To Activate Default Theme

### ISSUE THREAD

**Issue by XedinUnknown** [flurinduerst/WPDistillery#47]
The documentation contains no mention of what to do if it is desired to activate one of the default themes. I imagine that one would have to set `setup > cleanup > themes` to `false`. However, after that - I don't know.

**Comment by XedinUnknown** [comment]
Here's what I tried:
```yaml
theme:
  name: twentyseventeen
  rename: ""
  url: "https://downloads.wordpress.org/theme/twentyseventeen.1.1.zip"
```

Failure:
```
==> default: Downloading install package from https://downloads.wordpress.org/theme/twentyseventeen.1.1.zip...
==> default: Unpacking the package...
==> default: Installing the theme...
==> default: Warning: Destination folder already exists. "/var/www/wp/wp-content/themes/twentyseventeen/"
==> default: Theme install failed.
==> default: Error: No themes installed.
==> default: 
==> default: »»» aborting WPDistillery setup! 
==> default: bash: line 3: xit: command not found
```

**Comment by XedinUnknown** [comment]
Take 2:
```yaml
theme:
  name: twentyseventeen
  rename: ""
  url: ""
```

Output:
```
==> default: [=== INSTALL twentyseventeen ===]
==> default: »»» downloading twentyseventeen...
==> default: usage: wp theme install <theme|zip|url>... [--version=<version>] [--force] [--activate]
==> default: »»» aborting WPDistillery setup! 
==> default: bash: line 3: xit: command not found
```

**Comment by XedinUnknown** [comment]
Take 3:
```yaml
theme:
  name: twentyseventeen
  rename: ""
  url: "https://downloads.wordpress.org/theme/twentyseventeen.1.1.zip"

# Hoping that maybe it will get removed, and then re-downloaded
setup:
  cleanup: true
    themes: true
```
 Output:
```
==> default: [=== INSTALL twentyseventeen ===]
==> default: »»» downloading twentyseventeen...
==> default: Downloading install package from https://downloads.wordpress.org/theme/twentyseventeen.1.1.zip...
==> default: Unpacking the package...
==> default: Installing the theme...
==> default: Warning: Destination folder already exists. "/var/www/wp/wp-content/themes/twentyseventeen/"
==> default: Theme install failed.
==> default: Error: No themes installed.
==> default: 
==> default: »»» aborting WPDistillery setup! 
==> default: bash: line 3: xit: command not found
```

**Comment by XedinUnknown** [comment]
So, I haven't tried yet, but if I install *any* theme, will it say "Warning: Destination folder already exists" on re-provision, after I change some setting? If so, seems very inconvenient. Will it do the same for plugins too?

**Comment by flurinduerst** [comment]
Nice find! Right now, the cleanup is executed after the installation of the theme and will remove `twentyfifteen`, `twentysixteen`, `twentyseventeen`. So, right now, you can't enable the cleanup while installing one of these three themes using:
```
theme:
  name: twentyseventeen
  rename: ""
  url: "https://downloads.wordpress.org/theme/twentyseventeen.1.1.zip"
```
btw. your installing approach in Take 1 (posted in this comment) is correct.

I will fix this asap. Thanks!

**Comment by johnpitchko** [comment]
Copied comment from #57: 

Regarding the other bug, where install crashes when it tries to remove the default twentyseventeen theme, this error occurs even if I set theme cleanup to false in config.yml. Are these default themes being deleted regardless of what the themes value is in config.yml?

What was happening was that I was not installing a custom theme (WPSeed). Once I changed theme to true to install WPSeed, then the default WP themes were deleted successfully. In my situation, I didn't care about themes, so I did not install any. I would expect that some folks may not opt to install a theme in config.yml. If so, provisioning should not abort. Does that make sense?

My config.yml for reference:
```
setup:
  wp: true
  settings: true
  theme: false
  plugins: false
  cleanup: true
  # adjust what data you want to be deleted within the cleanup (required `cleanup: true`)
  comment: true
  posts: true
  files: true
  themes: false
```

**Comment by flurinduerst** [comment]
Here we go. Fixed in https://github.com/flurinduerst/WPDistillery/commit/06beddc482fba4469484839cb85ff598e04dc339 :) 

@XedinUnknown The way you tried to install the theme while removing (other) default themes, now works like a charm 👍  WPDistillery will now check if your theme is a default theme and won't delete it if so.

Feel free to add any questions/suggestions regarding this topic in here.
