### ISSUE TITLE
Web Server Provisioning Warning

### ISSUE THREAD

**Issue by XedinUnknown** [flurinduerst/WPDistillery#48]
In my `config.yml`, I changed `wpfolder` to `wp`. During provisioning, I get the following output:
```
==> default:  * Restarting web server apache2
==> default: AH00112: Warning: DocumentRoot [/var/www/public] does not exist
==> default: AH00112: Warning: DocumentRoot [/var/www/public] does not exist
```
Maybe, the value `public` is hard-coded somewhere?

### Update
Getting 404 when going to `http://wpdistillery.dev`. Vagrantfile and `wpsettings:url:` left untouched.

**Comment by XedinUnknown** [comment]
Changed `wp` back to `public`; still getting the warning. The domain is accessible now.

**Comment by flurinduerst** [comment]
Hi, thanks for the report

```
==> default:  * Restarting web server apache2
==> default: AH00112: Warning: DocumentRoot [/var/www/public] does not exist
==> default: AH00112: Warning: DocumentRoot [/var/www/public] does not exist
```
I'm aware of this (everyone receives this error at the moment) and will look into it. This error can be ignored safely at the moment. The config settings do not have any affect on this error. I guess the error appears because Vagrant doesn't have access to the synced folder yet within the starting process.

> In my config.yml, I changed wpfolder to wp. Getting 404 when going to http://wpdistillery.dev. Vagrantfile and wpsettings:url: left untouched.

`public` isn't hardcoded anywhere. I will have a look at this bug though. Thanks.

**Comment by XedinUnknown** [comment]
@flurinduerst, most probably, IMHO, the path to the docroot is in the Apache config, which probably isn't being modified anywhere during provisioning, and thus not being set to `wp` (in my case).

**Comment by XedinUnknown** [comment]
And by writing that, I don't necessarily mean that the docroot *should* be getting changed to match this config value. However, right now it looks like that value can be used to configure the actual docroot. Maybe it's the documentation that should be fixed, instead. Maybe just an indication that this value is there to adjust Distillery to match the underlying setup, decreasing its coupling to Scotchbox.

**Comment by flurinduerst** [comment]
fixed/updated in https://github.com/flurinduerst/WPDistillery/commit/0f9ff4d558d02b0c087fa89554f941639bd5ed69

Thanks!
