### ISSUE TITLE
Consider Flushing Rewirites

### ISSUE THREAD

**Issue by XedinUnknown** [flurinduerst/WPDistillery#49]
After setup, `.htaccess` is not generated, preventing permalinks from working.

Consider using [`wp rewrite flush`](http://wp-cli.org/commands/rewrite/flush/) with `--hard` to generate the `.htaccess` file as part of WP provisioning.

**Comment by flurinduerst** [comment]
Thanks for pointing this out. `wp rewrite flush` was added in [V1.8.0 ](https://github.com/flurinduerst/WPDistillery/blob/master/CHANGELOG.md#180-20122016) but was missing `--hard`. I fixed this in 1ec57ff7f5055d92539ec35c139a8e1193080b32
