### ISSUE TITLE
Installation not quite working ...

### ISSUE THREAD

**Issue by gitressa** [flurinduerst/WPDistillery#50]
Here is what I do, using Ubuntu 16.04:

$ mkdir WP-test
$ cd WP-test/
$ git clone https://github.com/flurinduerst/WPDistillery.git && mv WPDistillery/Vagrantfile Vagrantfile && mv WPDistillery/wpdistillery wpdistillery2 && rm -rf WPDistillery && mv wpdistillery2 wpdistillery

Change wpdistillery.dev to wpdistillery.test in ~/WP-test/wpdistillery/config.yml and ~/WP-test/Vagrantfile to avoid this issue: https://superuser.com/questions/919278/err-icann-name-collision-when-trying-to-use-localhost-dev-in-chrome

$ cd wpdistillery/
$ vagrant up --debug;
go to http://wpdistillery.test/ and get this page:

![wp-destil](https://cloud.githubusercontent.com/assets/3491208/26311083/4db3b032-3f03-11e7-8875-bf1eab84485a.png)

**Comment by skelly-jbfc** [comment]
I'm getting the exact same behavior with a windows host.

Creating a test page, the link will appear in that Home menu, but clicking the link takes you to a 404 Not Found page.

**Comment by flurinduerst** [comment]
Hi, thanks for reporting.

Can you provide your `config.yml` (make sure to delete passwords) and `Vagrantfile`? I'd like to have a look at it :) 

What version of Vagrant, Virtualbox and vagrant-hostsupdater are you using?

**Comment by gitressa** [comment]
Hi Flurin, I have since decided to not use WordPress, but try October CMS instead, so I have deleted the vagrant folder and all the files, including the WPDistillery config.yml, but here are the versions:

Vagrant 1.9.1
Virtualbox 5.1.22 r115126 (Qt5.5.1)
vagrant-hostsupdater 1.0.2

Vagrantfile is the default one in Scotch-Box:
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "scotch/box"
    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.hostname = "scotchbox"
    config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777", "fmode=666"]
    
    # Optional NFS. Make sure to remove other synced_folder line too
    #config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777","fmode=666"] }
end
```

**Comment by flurinduerst** [comment]
There is nothing wrong with your installation. WordPress is installed :) You just didn't run gulp yet.Can you access the wpdistiller.test/wp-admin to Login?

If you didn't change the default theme ([WPSeed](https://wpseed.org)) please follow the Theme-Setup at https://github.com/flurinduerst/WPSeed/blob/master/README.md#requirements

Also, if your navigation-links aren't working correctly. [Refresh Permalinks](http://www.inmotionhosting.com/support/edu/wordpress/wordpress-features/reset-permalinks)
