### ISSUE TITLE
Import ACF JSON file after plugins install

### ISSUE THREAD

**Issue by jordanboston** [flurinduerst/WPDistillery#54]
As a feature request, it would be great to be able to import all our default *ACF field groups* and fields on install.  We can download/export a json file that can be imported into a new WordPress install, or php to add to functions.php with the same data.  It would be awesome to define this in the config and then import all of that from a git repo with the json data.  

https://www.advancedcustomfields.com/resources/register-fields-via-php/

This would have to be after the plugin installs of course, but would make the whole process even better.  Thanks!

**Comment by ShaneShipston** [comment]
Any reason you don't want to use the local JSON option offered? This way you can just have a acf-json folder within your theme that holds all your field groups you may need.

https://www.advancedcustomfields.com/resources/local-json/

**Comment by jordanboston** [comment]
Good point.  I guess this automation is not really needed.  Thanks
