### ISSUE TITLE
Combine WPDistillery and Bedrock

### ISSUE THREAD

**Issue by schilke** [flurinduerst/WPDistillery#55]
Not directly WPDistillery related - apologies if this might not be the proper place - but I thought to ask here if someone else has a similar request: Due to the fact that I'd like to start a project with Foundation I wanted to combine [Bedrock](/roots/bedrock/) and WPDistillery. I had a look if someone else did this already - with no luck.
Any hints and/or suggestions for a good starting point?
The most important feature to me would be the improved directory structure (besides usage of Foundation 6).

**Comment by flurinduerst** [comment]
Well you can use wp-cli with bedrock. So if you edit wpdistillery.sh to using the bedrock related paths this should work. Altough I don't see your purpose in this. Why not just use Foundation + WPDistillery or Bedrock with Trellis?
