### ISSUE TITLE
==> default: Error: Couldn't extract WordPress archive. unable to decompress gzipped phar archive "/tmp/wp_59c858868ea2d.tar.gz" to temporary file

### ISSUE THREAD

**Issue by brooke-heaton** [flurinduerst/WPDistillery#56]
Vagrant fails each time with this error. I am not clear of the cause.

**Comment by brooke-heaton** [comment]
Evidently, this is a new package error: https://github.com/wp-cli/wp-cli/issues/4370

**Comment by brooke-heaton** [comment]
I am on PHP 7.1.8 (cli) (built: Aug  7 2017 15:02:45) ( NTS )

**Comment by Annalyn** [comment]
Having a problem on this as well.
I always get this error:
default: Error: Couldn't extract WordPress archive. unable to decompress gzipped phar archive "/tmp/wp_59c93b879c826.tar.gz" to temporary file

**Comment by ShaneShipston** [comment]
It seems to be tied to the current version of WordPress you can try changing the locale to something other than en_us within the config file or change the version from latest to nightly.

**Comment by flurinduerst** [comment]
Thanks @bheatonf1 for letting us know and providing the wp-cli related issue. 
This is an issue created by wp-cli interacting with specific PHP distros.  

I created a gist with a hotfix that should help for now (untested).
Please try replacing `wpdistillery/wpdistillery.sh` with https://gist.github.com/flurinduerst/b5b8dad796b64a3a45bca06ce7ffc401 and try again.

As stated in https://github.com/wp-cli/wp-cli/issues/4370#issuecomment-332245998 this should be fixed within the new wp-cli version releasing october 17th:
> We'll publish WP-CLI v1.4.0 on Tuesday, October 17th. For now, those affected can use wp cli update --nightly.

**Comment by johnpitchko** [comment]
Hello I tried doing a clean install of wpdistillery using the gist provided by @flurinduerst . Unfortunately, I received the same error: `==> default: Error: Couldn't extract WordPress archive. unable to decompress gzipped phar archive "/tmp/wp_59e495d080334.tar.gz" to temporary file`

**Comment by johnpitchko** [comment]
I replaced the provision.sh to use wp-cli-nightly rather than standard wp-cli. Gist is available here: https://gist.github.com/johnpitchko/f80f7c1a2fdf59d4b80c1f7961243ebd

Understand this is supposed to be fixed on the release tomorrow but for impatient souls like myself, you can use this hahaha.

**Comment by flurinduerst** [comment]
error is finally fixed with the new version of WP-CLI :)

**Comment by brooke-heaton** [comment]
Fantastic. Thanks @flurinduerst !
