### ISSUE TITLE
Permission denied in phar://usr/local/bin/wp/php/WP_CLI/FileCache.php

### ISSUE THREAD

**Issue by dikkedimi** [flurinduerst/WPDistillery#57]
Installation aborts with this notification repeating multiple times:

```
==> default: PHP Warning:  mkdir(): Permission denied in phar:///usr/local/bin/wp/php/WP_CLI/FileCache.php on line 265
==> default: Warning: mkdir(): Permission denied in phar:///usr/local/bin/wp/php/WP_CLI/FileCache.php on line 265
```
and then at the end
```
==> default: Warning: The package could not be installed. "No valid plugins were found."
==> default: Plugin install failed.
==> default: Error: No plugins installed.
==> default:
==> default: »»» aborting WPDistillery setup!
==> default: bash: line 5: xit: command not found
```

**Comment by johnpitchko** [comment]
Yes I am also encountering this issue, plus one or two others:

```
==> default: Downloading WordPress 4.8.2 (en_US)...
==> default: PHP Warning:  mkdir(): Permission denied in phar:///usr/local/bin/wp/php/WP_CLI/FileCache.php on line 265
==> default: md5 hash verified: 2e8744a702a3d9527782d9135a4c9544
==> default: Warning: PharData failed, falling back to 'tar gz' (unable to decompress gzipped phar archive "/tmp/wp_59f47fd77a40c.tar.gz" to temporary file)
==> default: Success: WordPress downloaded.
==> default: »»» creating wp-config...
==> default: Success: Generated 'wp-config.php' file.
==> default: »»» installing wordpress...
==> default: Success: WordPress installed successfully.
==> default: Success: Updated user 1.
==> default: »»» configure settings...
==> default: » timezone:
==> default: Success: Updated 'timezone' option.
==> default: Success: Updated 'timezone_string' option.
==> default: » permalink structure:
==> default: Success: Rewrite rules flushed.
==> default: Success: Rewrite structure set.
==> default: Warning: Regenerating a .htaccess file requires special configuration. See usage docs.
==> default: Success: Rewrite rules flushed.
==> default: » description:
==> default: Success: Updated 'blogdescription' option.
==> default: » image sizes:
==> default: Success: Value passed for 'thumbnail_size_w' option is unchanged.
==> default: Success: Value passed for 'thumbnail_size_h' option is unchanged.
==> default: Success: Value passed for 'medium_size_w' option is unchanged.
==> default: Success: Value passed for 'medium_size_h' option is unchanged.
==> default: Success: Value passed for 'large_size_w' option is unchanged.
==> default: Success: Value passed for 'large_size_h' option is unchanged.
==> default: Success: Updated 'convert_smilies' option.
==> default: » front page:
==> default: Success: Created post 3.
==> default: Success: Updated 'page_on_front' option.
==> default: Success: Updated 'show_on_front' option.
==> default: >>> skipping theme installation...
==> default: [=== CLEANUP ===]
==> default: »»» removing default comment...
==> default: Success: Deleted comment 1.
==> default: »»» removing default posts...
==> default: Success: Deleted post 1.
==> default: Success: Deleted post 2.
==> default: »»» removing WP readme/license files...
==> default: »»» removing default themes...
==> default: Deleted 'twentyfifteen' theme.
==> default: Success: Deleted 1 of 1 themes.
==> default: Deleted 'twentysixteen' theme.
==> default: Success: Deleted 1 of 1 themes.
==> default: Warning: Can't delete the currently active theme: twentyseventeen
==> default: Error: No themes deleted.
==> default: »»» aborting WPDistillery setup!
==> default: bash: line 5: xit: command not found
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by flurinduerst** [comment]
@dikkedimi what version of WP-CLI are you running on this installation? Could you provide your `config.yml` (make sure to remove passwords first)?

@johnpitchko You're running into the problem of trying to install a default WP-theme after running the theme cleanup (= uninstalling default themes). This refers to https://github.com/flurinduerst/WPDistillery/issues/47 and will be fixed in next few days.

**Comment by SimeonGriggs** [comment]
I'm getting this error too. Basically makes the whole thing pointless.

**Comment by flurinduerst** [comment]
@SimeonGriggs please provide your version of `WP-CLI`, `Vagrantfile` and `config.yml`. I'm trying to help here, but that one-liner doesn't help a lot to be honest.

**Comment by SimeonGriggs** [comment]
If I follow the setup instructions as-is, fresh install, with no modifications it gives the same error:

`==> default: PHP Warning:  mkdir(): Permission denied in phar:///usr/local/bin/wp/php/WP_CLI/FileCache.php on line 265`

I can send you a screencast if you like.

Edit: Curiously if I run `vagrant reload --provision` on the same box it then completes, but with a bunch of similar errors like

`==> default: PHP Warning:  mkdir(): Permission denied in phar:///usr/local/bin/wp/php/WP_CLI/FileCache.php on line 265`
`==> default: Warning: mkdir(): Permission denied in phar:///usr/local/bin/wp/php/WP_CLI/FileCache.php on line 265`

**Comment by flurinduerst** [comment]
Thanks @SimeonGriggs 

I was able to replicate your error, it does not interrupt the installation or cause any problems though. 

The following error is caused because PHP sees a phar file as a mounted filesystem.
and your cache directory probably can't be written. I will look into this, but it does not abort the installation process.

```
==> default: PHP Warning:  mkdir(): Permission denied in phar:///usr/local/bin/wp/php/WP_CLI/FileCache.php on line 265
==> default: Warning: mkdir(): Permission denied in phar:///usr/local/bin/wp/php/WP_CLI/FileCache.php on line 265
```

What does abort your installation is this error, which has nothing to do with the first one.

```
==> default: Warning: The package could not be installed. "No valid plugins were found."
==> default: Plugin install failed.
==> default: Error: No plugins installed.
==> default:
==> default: »»» aborting WPDistillery setup!
==> default: bash: line 5: xit: command not found
```

This error may occur if:
* There is an invalid source-path to a plugin or another package. Could you provide a few lines before that error occurred? It would be interesting to see at what point in the process it occurred.
* you try to run provisioning on an already completed setup using `vagrant up --provision` sometimes. 

Conclusion: altought there is this `Permission denied` error, everything is working fine. I will look into this error though and fix it asap.

**Comment by SimeonGriggs** [comment]
Ah! Right. Okay then. 

Think I've got it working for the most part now.

I was also getting intermittent errors while trying over and over, sometimes it couldn't remove posts, or comments, or themes. Not sure if these are related to permissions as well.

**Comment by flurinduerst** [comment]
That's great to hear!
You will get this error when trying to delete already deleted posts/comments. Within the cleanup-process (there's an option for that in `config.yml`) WPDistillery is trying to delete the default posts/comments/themes. If you already ran WPDistillery before, those items are already deleted. If you want a completely fresh, new install, destroy your box using `vagrant destroy` which also deletes the local database.

**Comment by SimeonGriggs** [comment]
Ah, makes sense. And yeah I was doing provisions and destroys over and over while trying to sort this out. Think it's all good now!

**Comment by johnpitchko** [comment]
@flurinduerst I am using the latest version of WP-CLI.
```
==> default: == WordPress CLI info ==
==> default: PHP binary:	/usr/bin/php7.0
==> default: PHP version:	7.0.19-1+deb.sury.org~trusty+2
==> default: php.ini used:	/etc/php/7.0/cli/php.ini
==> default: WP-CLI root dir:	phar://wp-cli.phar
==> default: WP-CLI vendor dir:	phar://wp-cli.phar/vendor
==> default: WP_CLI phar path:	/
==> default: WP-CLI packages dir:
==> default: WP-CLI global config:
==> default: WP-CLI project config:
==> default: WP-CLI version:	1.4.0
==> default: WP-CLI Update successful
```
Regarding the other bug, where install crashes when it tries to remove the default twentyseventeen theme, this error occurs even if I set theme cleanup to false in config.yml. Are these default themes being deleted regardless of what the `themes` value is in config.yml?

What was happening was that I was not installing a custom theme (WPSeed). Once I changed `theme` to true to install WPSeed, then the default WP themes were deleted successfully. In my situation, I didn't care about themes, so I did not install any. I would expect that some folks may not opt to install a theme in config.yml. If so, provisioning should not abort. Does that make sense?

My config.yml for reference:
```
setup:
  wp: true
  settings: true
  theme: false
  plugins: false
  cleanup: true
  # adjust what data you want to be deleted within the cleanup (required `cleanup: true`)
  comment: true
  posts: true
  files: true
  themes: false
```

**Comment by flurinduerst** [comment]
@johnpitchko thanks a lot for this, I will look into it in detail and provide you with an answer asap. To keep things clear, please add this comment to https://github.com/flurinduerst/WPDistillery/issues/47 so we can talk about the `mkdir(): Permission denied` error in this issue and about the theme-handling in the other one :)

**Comment by johnpitchko** [comment]
Yes will do right now!

**Comment by leogaggl** [comment]
Getting this error as well - latest wp-cli stable on both systems (local and remote). 

just running a core, theme and plugin update.

**Comment by flurinduerst** [comment]
Altought the bug doesn't break anything, it also occurs on every plugin-installation inside the installation-process . Will look into this asap. Note that WPDistillery works as expected even this error shows up from WP-CLI.

**Comment by flurinduerst** [comment]
reference: https://github.com/wp-cli/wp-cli/issues/4633#issuecomment-363434058
