### ISSUE TITLE
Installation with Scotch Box Pro

### ISSUE THREAD

**Issue by Lego2012** [flurinduerst/WPDistillery#58]
Just tried the install with Scotch Box Pro. In Vagrantfile I changed to `config.vm.box = "scotch/box-pro"` and startet the installation. It seems that it works.

Do you have another recommendation?

Tnx.

**Comment by flurinduerst** [comment]
Hi @Lego2012 

That's exactly how you should do it :) 😎
Let me know if you stumble upon any problems with scotch-box while using WPDistillery.
