### ISSUE TITLE
Poll: Would you use a multisite-feature for WPDistillery?

### ISSUE THREAD

**Issue by flurinduerst** [flurinduerst/WPDistillery#59]
With https://github.com/flurinduerst/WPDistillery/pull/45 we have a pull-request for a multisite feature within WPDistillery. Many thanks to  @pjohanneson for the contribution.

WPDistillery aims to be as clean and minimal as possible. It should have everything we really need, but nothing more. Adding the WP-Multisite feature to WPDistillery means, that we add a bunch of options and some code that is only relevant if you're creating a multisite installation. If this feature is used a lot, I'm happy to add it to WPDistillery within the next major release. If not, we might find a solution to add the multisite feature using an optional external source or swap all multisite-relevant files into its own folder.

Please add your answer to this form, so we'll get some insights about the need of this feature.

https://goo.gl/forms/TsDxBINXydOVJ3XJ3

Feel free to add comments, ideas, thoughts in this issue.

**Comment by johnpitchko** [comment]
I voted 'no', even though I was one who did try to use WPDistillery recently for a multisite project. I agree with the idea of keeping the code as clean and minimal as possible. May I suggest the following:

1. Keep @pjohanneson 's fork separate for those who want a multisite install. Add a link in the WPDistillery README.md to this fork to direct folks looking for a multisite option.
2. How is multisite added to a default WP install? Add a link to the WPDistillery README.md to the official WordPress documentation for adding multisite capabilities.

Using the options above eliminates the need for the PR, but directs users to the proper resources if they have the requirement.

**Comment by pjohanneson** [comment]
I like @johnpitchko's approach of keeping the Multisite in a separate fork (even a separate project). That way the code stays clean and minimal.

**Comment by flurinduerst** [comment]
I will not merge this PR as we decided to keep WPDistillery as clean as it is. I will add a note to the readme though and link to the PR. Thanks a lot to @pjohanneson for the contribution. Highly appreciate it! 🎉
