### ISSUE TITLE
RSS Reading Doesn't Work

### ISSUE THREAD

**Issue by XedinUnknown** [flurinduerst/WPDistillery#61]
First of all, thanks @flurinduerst for featuring my name in the release notes for [2.2.0](https://github.com/flurinduerst/WPDistillery/releases/tag/2.2.0); I'm glad I could help.

Now to the point. I understand that this is not really an issue with WPDistillery, but I would like to point out that a fresh install does not allow usage of SimplePie, or anything that relies on `libxml`. It's simply not installed in the box. The fix is outlined in https://github.com/scotch-io/scotch-box/issues/311#issuecomment-318643997. However, perhaps you would like to add this to the provisioning routine, because it's kinda necessary to make some popular features of WordPress work.

Try this:

```bash
# https://github.com/oerdnj/deb.sury.org/issues/56
sudo LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php

# https://github.com/scotch-io/scotch-box/issues/275
sudo rm /etc/apt/sources.list.d/ondrej-php5-5_6-trusty.list

# Update sources
sudo apt-get update

# Install extra packages
sudo apt-get install -y \
    php-curl \
    php7.0-xml \
    php7.0-mbstring

# Restart server the Ubuntu way
sudo apache2ctl restart
```

This is from a script that I wrote which would convert ScotchBox 2 to PHP 7, and it used to work very well.

Another thing is that I didn't find the timezone in the `php.ini` config. This is required in PHP 7, and I'm not sure how, but everything seems to be working without it for now. Just in case it doesn't one day work, you can use this to add the timezone during provisioning (also from the same script):

```bash
sudo sed -i 's/^;\(date\.timezone\) =\s*$/\1 = "Europe\/Paris"/g' /etc/php/7.0/cli/php.ini
sudo sed -i 's/^;\(date\.timezone\) =\s*$/\1 = "Europe\/Paris"/g' /etc/php/7.0/apache2/php.ini
```

**Comment by XedinUnknown** [comment]
Bump. Was working with Scotchbox, googled the problem, and find my own answer.

**Comment by flurinduerst** [comment]
I really appreciate your input/feedback @XedinUnknown but I just can't "fix" issues that come from scotchbox itself. Sure, technically we can do this – no problem – but editing the scotchbox configuration itself should not be the way to go for WPDistillery. We do indeed update WP-CLI, which kind of is "editing the scotchbox configuration" but that's because it is absolutely essential to make WPDistillery work. I agree, that this should be implemented into scotchbox.

**Comment by XedinUnknown** [comment]
@flurinduerst, support for specific software or extensions, such as SimplePie or WordPress, is not the goal of Scotchbox. On the other hand, you do describe WPD as something that makes WordPress work on Scotchbox (correct me if I'm wrong). Therefore, with the goal of Scotchbox fulfilled, I believe it is eventually the responsibility of WPD to make WP work, including its core features. One of those features, I believe, is the ability to import feeds. In fact, the vanilla dashboard itself uses RSS to display news. I urge you to re-consider, especially since the fix is simple.

By the way, if the relationship between SimplePie and WordPress is debatable, I am absolutely sure that issuing cURL requests is definitely a part of WP native functionality.

**Comment by XedinUnknown** [comment]
Apparently, the issue with `libxml` is getting resolved to day as part of scotch-io/scotch-box#311. Who knows, maybe the issue with cURL will be resolved too.

**Comment by flurinduerst** [comment]
That's great news. According to the docs and nicks answers on the [issue](https://github.com/scotch-io/scotch-box/issues/311), this should be fixed now in v3.5 - Can you confirm this by testing it on Scotch Box 3.5?

**Comment by XedinUnknown** [comment]
Will try to do this later on this week. Probably Saturday. If not, after the 29th.

**Comment by flurinduerst** [comment]
That's great. Highly appreciated, thank you!

**Comment by flurinduerst** [comment]
@XedinUnknown Have you been able to test it? Any news on that? :)

**Comment by XedinUnknown** [comment]
I'm sorry, I don't know when I will be able to test this. I am on a super tight deadline to finish a huge project that I lead. I was thinking to use WPD for testing the project in WP, but I found that a different approach suits me better: [dhii/scotch-on-rocks][]. Being able to have everything under version control is kinda important. I fixed all problems in my provisioning scripts there. So in truth, I don't know if I will continue using WPD. But I hope that it helps other people, who experience the same issues I had.

Again, I am sorry.

[dhii/scotch-on-rocks]: https://github.com/Dhii/scotch-on-rocks

**Comment by flurinduerst** [comment]
No problem. Will test this myself asap.

**Comment by XedinUnknown** [comment]
Stumbled across this again. ScotchBox appears to have resolved the issue somewhere [here](https://github.com/scotch-io/scotch-box/issues/311#issuecomment-370054687), but there's not even the extension available when I installed with WPDistillery today. Could it be that somehow you are using an old version of scotchbox?
