### ISSUE TITLE
Error while setting up WPDistillery

### ISSUE THREAD

**Issue by hetenho** [flurinduerst/WPDistillery#64]
I get an error when running `vagrant up`:

`Parse error: syntax error, unexpected '}', expecting end of file in /var/www/public/wp-content/themes/WPSeed/functions/functions-backend.php on line 80`

**Comment by flurinduerst** [comment]
this issues is related to the theme https://github.com/flurinduerst/WPSeed, not to WPDistillery itself. I just fixed it by removing a unneeded brace in the theme-file. Thanks for letting me know.
