### ISSUE TITLE
WP-Cli

### ISSUE THREAD

**Issue by kubarazny** [flurinduerst/WPDistillery#65]
How could I use WP-cli in this vagrant to install theme?

**Comment by ShaneShipston** [comment]
Log into the box with `vagrant ssh` then go to the root of the project `cd /var/www/public` and run the standard theme install command `wp theme install {yourTheme}`

**Comment by flurinduerst** [comment]
This is related to [ScotchBox](https://github.com/scotch-io/scotch-box) and not WPDistillery. Therefore I'm closing this issue.
