### ISSUE TITLE
default: wpdistillery.sh: line 67: cd: public: No such file or directory

### ISSUE THREAD

**Issue by donaldCull** [flurinduerst/WPDistillery#68]
Hi,
Trying to setup wpdistillery and received this 
`error.default: wpdistillery.sh: line 67: cd: public: No such file or directory.`

I tried creating this directory manually and received.
    `default: Warning: Failed to create directory '/root/.wp-cli/cache/': mkdir(): Permission denied.`

Unsure how to proceed.

Thanks Don

**Comment by flurinduerst** [comment]
Hi, this is an uncritical bug (caused by vagrant/scotchox settings) that does not abort the installation. See my answer in https://github.com/flurinduerst/WPDistillery/issues/57#issuecomment-340831944. (Only the first code-snippet is relevant in this case). 

I will look into this as soon as I find the time to though.

**Comment by donaldCull** [comment]
Hi I read your comment.  It looks to be relevant to the second error but do I need to create a public folder manually?

Thanks Don
On 2 Mar 2018, at 8:24 PM, Flurin Dürst <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #68<https://github.com/flurinduerst/WPDistillery/issues/68>.

**Comment by flurinduerst** [comment]
Wow, I did totally missread your comment. Sorry!
Actually there was a bug in the setup-file where the `public` folder was not being created, so the installer could not proceed. The root folder should be created by scotchbox but didn't and my fallback didn't run. I just fixed this in 5c8af66305fec042d8b11617f01f685168618d00. Thanks a lot for letting me  know!
