### ISSUE TITLE
project not displaying correctly

### ISSUE THREAD

**Issue by donaldCull** [flurinduerst/WPDistillery#69]
Hi,

After running Vagrant up inside of my project I receive `default: Warning: Failed to create directory '/root/.wp-cli/cache/': mkdir(): Permission denied`. about 11 times and also receive     `default: Warning: Regenerating a .htaccess file requires special configuration. See usage docs.`  The rest of the installation continues as normal but when I open http://192.168.33.10/ it looks like this
![screen shot 2018-03-04 at 6 42 26 pm](https://user-images.githubusercontent.com/20510711/36943861-7e9afb5a-1fdc-11e8-988a-c1831f18e608.png)
![screen shot 2018-03-04 at 6 49 24 pm](https://user-images.githubusercontent.com/20510711/36943882-ea90b278-1fdc-11e8-8546-2fe3b3ddc93d.png)

I am unable to get to the admin login from here as well.

Thanks Don

**Comment by donaldCull** [comment]
I have seen that there is another issue related to this mkdir() permission denied but from what I have seen of that thread everything was still working fine.

**Comment by flurinduerst** [comment]
Hi donaldCull

You're correct. The mkdir error is ugly, and will be fixed asap - but doesn't break anything. See https://github.com/flurinduerst/WPDistillery/issues/57

What you see posted in your sceenshots is a completed WPDistillery-run. Everything worked out fine, but you didn't follow the instructions on the installed Theme which is WPSeed by default. You have to run npm and gulp with WPSeed. Please check the docs at https://github.com/flurinduerst/WPSeed

Obivously you're free to use any theme you want with WPDistillery, it doesn't have to be WPSeed, it's just the default :)

Not sure about:

> I am unable to get to the admin login from here as well.

What exactly do you get at wpdistillery.vm/wp-admin?

**Comment by donaldCull** [comment]
Hi,

Sorry I didn’t realise there were extra steps for theme setup I will follow them.  Perhaps in the setup steps there could be a link to the WP-seed setup.  Before I was unable to reach the login screen but I realised that I was using http://wpdistillery.vm/admin and not wpdistillery.vm/wp-admin my apologies.  Thanks for all your help.

Thanks Don.

On 4 Mar 2018, at 8:40 PM, Flurin Dürst <notifications@github.com<mailto:notifications@github.com>> wrote:

wpdistillery.vm/wp-admin

**Comment by flurinduerst** [comment]
No worries. There actually is a Link to the WPSeed Docs: https://github.com/flurinduerst/WPDistillery#what-is-wpdistillery :)
