### ISSUE TITLE
Jetpack custom post types not available

### ISSUE THREAD

**Issue by johnpitchko** [flurinduerst/WPDistillery#73]
Hello, just did two clean installs of WPDistillery and enabled Jetpack in Development Mode (so no connection to Wordpress.com). I then enabled the two built in custom post types (CPTs) in Jetpack (Portfolio and Testimonials). Activation appears to work okay, but the post types do not appear in the Admin screen, or in *Settings > Writing*.

No idea if the issue is with WPDistillery, Scotchbox, or Jetpack, but opening a low priority issue to do some testing and to ask if anyone else can replicate this issue.
![wpdistillery-jetpack-cpt-enabled](https://user-images.githubusercontent.com/7190681/37254230-dbc3e048-2500-11e8-86ae-b8d860eed76c.png)
![wpdistillery-cpt-missing-in-settings](https://user-images.githubusercontent.com/7190681/37254231-dbda880c-2500-11e8-9ea1-cc27d490a3ba.png)

**Comment by johnpitchko** [comment]
A brief update; here are the results of the debugging work I conducted over the past few days:

* The issue is not related to my custom theme. I switched to a different theme (Argent), which is listed to be compatible with Jetpack Portfolios, and encountered the same issue.

* Other custom post types are allowed. I installed the *CPT UI* plugin and created my own dummy custom post type through Wordpress admin. It displays correctly in the admin bar after creation.

* I manually copied the `register_custom_post_type()` function for the jetpack-portfolio custom post type from Jetpack and ran it manually in my functions.php. The Portfolio post type did appear in the admin bar.

My current conclusion is that, even though it is enabled in the Jetpack settings, something is preventing the Jetpack code from executing and thus registering the post type. I am now trying to step through the Jetpack source to discover why that is.

Also I did enable the Jetpack Dev Mode setting, so that __may__ be an issue. However I recall seeing a few posts on the internet stating that the CPT module in Jetpack should still work even in Dev Mode.

**Comment by johnpitchko** [comment]
Did some more digging. Can confirm that the *Content Options* panel in Customizer (part of Jetpack) also does not load.

**Comment by flurinduerst** [comment]
Hey @johnpitchko 
Thanks for your troubleshooting! 
I'm trying to help:

When looking at https://jetpack.com/for/hosts/requirements/ I found 

> Requests from WordPress.com through the XML-RPC interface may not be blocked.

Not 100% sure, but this might be the problem. 
See https://github.com/flurinduerst/WPDistillery/issues/61 and https://github.com/scotch-io/scotch-box/issues/311#issuecomment-318643997. This bug should now be fixed within Scotch Box 3.5 as `libxml
` is now a default module. Did you test this on Scotch Box 3.0 or 3.5?

**Comment by johnpitchko** [comment]
Thanks @flurinduerst I am using the latest version of Scotchbox from their website, believe this is 3.5.

**Comment by johnpitchko** [comment]
Ok good news and bad news.

The good news is that I installed [VCCW](http://vccw.cc), which is another pre-configured Wordpress dev environment for Vagrant, installed Jetpack, and enabled Portfolios custom post type. **Portfolio** is now available on the nav bar! Also, **Content Options** is available in the Customizer when using my custom theme!

Bad news means that this issue is obviously with Scotchbox. I will open an issue there and close the issues I opened here and with Jetpack.
![customizer-vccw](https://user-images.githubusercontent.com/7190681/37748235-ba929bee-2d48-11e8-817d-16e56a2c31cb.png)
![jetpack-vccw](https://user-images.githubusercontent.com/7190681/37748236-baae3f7a-2d48-11e8-8c10-69b417421d18.png)



Thanks for your help @flurinduerst, but I think this one is out of your hands !!!

**Comment by johnpitchko** [comment]
I think I closed this one in haste (sorry I have a 3 month old and am suffing a lack of sleep!)

While Jetpack CPTs work fine using VCCW, the issue might still be with how WPDistillery installs/configures Wordpress.

So I'll keep this issue open while I also [work with the Scotchbox team](https://github.com/scotch-io/scotch-box/issues/373).
