### ISSUE TITLE
windows 10: initial vagrant up fails on creation of wpconfig 

### ISSUE THREAD

**Issue by ghost** [flurinduerst/WPDistillery#75]
windows 10 FCU, running vagrant up command (first time) as administrator with the following result:

    default: [=== INSTALL WORDPRESS ===]
    default: »»» downloading WordPress...
    default: Downloading WordPress 4.9.4 (en_US)...
    default: Warning: Failed to create directory '/root/.wp-cli/cache/': mkdir(): Permission denied.
    default: md5 hash verified: ff84abd9ec38b93ef0ea09b05e85467b
    default: Success: WordPress downloaded.
    default: »»» creating wp-config...
    default: ERROR
    default:  1045 (28000)
    default: : Access denied for user 'root'@'localhost' (using password: YES)
    default:
    default: »»» aborting WPDistillery setup!
    default: bash: line 5: xit: command not found
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

C:\Users\user\wpdstl01>

**Comment by flurinduerst** [comment]
Hi @sfthurber

Can you provide your `Vagrantfile` and tell us, if you're using the default configuration or if you edited some settings (and if so, what are the changes you've made)?

Are you able to ssh into the Virtual Machine?

**Comment by ghost** [comment]
100% default

**Comment by flurinduerst** [comment]
It looks like you don't have the correct permissions. Can you access the box via `vagrant ssh` and try to execute some wp-cli commands manually? Also, what permissions do you have to the public folder inside the vagrant box?
