### ISSUE TITLE
Timed out after vagrant up

### ISSUE THREAD

**Issue by yongchengzhu** [flurinduerst/WPDistillery#76]
After 'vagrant up' successful, I still cannot access the site via http://192.168.33.10/

Is there something I'm missing?

**Comment by flurinduerst** [comment]
With the information you provided, we don't know. To be able to help you, please tell us
- Can you access ScotchBox itself? Like, only run ScotchBox without WPDistillery
- What version of ScotchBox, OS, Virtualbox are you using?
- Can you access the site via the URL in the `Vagrantfile` ?
- Is vagrant-hostupdater running as expected and does it create the entry in the hostfile when running vagrant up?

**Comment by 981014** [comment]
Scotch Box version is 3.5.
Operating System is Windows 7.
Virtual Box version is 5.2.8.
No I cannot access URL nor IP in the Vagrantfile.
Vagrant-hostupdater is working properly.

**Comment by flurinduerst** [comment]
Since you haven't replied in one month, I'm closing this. Feel free to comment on this issue if you still need help on this.
