### ISSUE TITLE
How can I remove plugins?

### ISSUE THREAD

**Issue by Suhkha** [flurinduerst/WPDistillery#82]
I can upload new plugins during my development but how can I remove those that I can use anymore?

Thanks!

**Comment by Suhkha** [comment]
Never mind, i change the wpdistillery.sh in the section: Plugins
`
printf "${BLU}»»» deleting plugins${NC}\n"
for entry in "${CONF_plugins_delete[@]}"
do
  wp plugin delete $entry
done
`
And in the config.yml, add the list: 
plugins_delete:
- plugin-name-1
- plugin-name-2

And finally run again:
`bash wpdistillery.sh`

Hope this help someone.

**Comment by flurinduerst** [comment]
Hey Suhkha

I'm not sure what you're trying to accomplish. WPDistillery is made for the initial setup of your project. Adding and deleting plugins afterwords should be done via WP-CLI or in the WordPress Backend.

If there are plugins in the default config you don't want, just remove them from the `config.yml`-File.
