### ISSUE TITLE
Add Remote DB Support

### ISSUE THREAD

**Issue by adamrl84** [flurinduerst/WPDistillery#84]
On line 82 in wpdistillery.sh you could change

`wp core config --dbname=$CONF_db_name --dbuser=$CONF_db_user --dbpass=$CONF_db_pass --dbprefix=$CONF_db_prefix --locale=$CONF_wplocale`

to become

`wp core config --dbname=$CONF_db_name --dbuser=$CONF_db_user --dbpass=$CONF_db_pass --dbprefix=$CONF_db_prefix --locale=$CONF_wplocale --dbhost=$CONF_db_host`

(last part adds **db_host**)

and then the corresponding YAML beginning on line 31:

db:
  host: 192.168.1.12
  name: whatever
  user: user
  pass: password
  prefix: wp_

This would be a useful feature, and you could just leave it as localhost by default.

A remote database is a requirement where I work, for various different reasons.

**Comment by flurinduerst** [comment]
sounds good to me. Feel free to create a pull-request after testing it ;)

Thanks!
