### ISSUE TITLE
Wordpress runs but i can't open any post,comments ,archives.. etc

### ISSUE THREAD

**Issue by evanvas** [flurinduerst/WPDistillery#89]
Hi, 
OS: Windows 10
using vagrant and virtualbox.

I'm currently running wordpress 4.2 for a web security course and am able to run the site using virtual box. For some reason i am unable to open any post. i can however create post using the wordpress dashboard but it wont let me see the post on the site.
i have tried redoing the entire process multiple times with no success. please help. 
 

Example error: Not Found
The requested URL /hello-world/ was not found on this server.
Apache/2.4.18 (Ubuntu) Server at wpdistillery.vm Port 80

**Comment by ShaneShipston** [comment]
It sounds like the permalink needs to be updated. Try going to Settings > Permalinks within WordPress and saving that form.

**Comment by evanvas** [comment]
You are Amazing ! Thank you ! <3
