### ISSUE TITLE
update structure

### ISSUE THREAD

**Issue by flurinduerst** [flurinduerst/WPDistillery#9]
Let me know your pro/cons on this: 

To provide a better overview and have a folder instead of two files in the www-root, put all files into a wpdistillery folder while also splitting up the config.yml into multiple files. 

```
wpdistillery/
|-- .gitignore
|-- CHANGELOG.md
|-- README.md
|-- LICENSE.txt
|-- setup.sh
|-- config/
    |-- installation.yml
    |-- plugins.yml
    |-- settings.yml
    |-- setup.yml
    |-- theme.yml
```

alternatively

```
wpdistillery/
|-- .gitignore
|-- CHANGELOG.md
|-- README.md
|-- LICENSE.txt
|-- setup.sh
|-- config.yml
```

**Comment by mawiswiss** [comment]
Good idea. I'm working on a small deployment script and I'm not happy with the name "config.yml" (it could be everything).
I personally would rename the "config"-folder into wpdistillery_config or something more specific.

**Comment by JoshMoreno** [comment]
+1 Much more semantic. Would be easier to understand and navigate imo

**Comment by flurinduerst** [comment]
done with WPDistillery V2.0 :)
