### ISSUE TITLE
Clean install, Call to undefined function wp_dashboard_setup() when trying to access /wp-admin

### ISSUE THREAD

**Issue by donkkis** [flurinduerst/WPDistillery#92]
Hi,

After fresh installation, i'm not able to log in to the admin dashboard. Instead, I get the error:

`Fatal error: Uncaught Error: Call to undefined function wp_dashboard_setup() in /var/www/public/wp-admin/index.php:15 Stack trace: #0 {main} thrown in /var/www/public/wp-admin/index.php on line 15
`
Mostly, i am using default settings in config.yml, with the following exceptions:

  theme: false
  plugins: false
  cleanup: false

Furthermore, in Vagrantfile I am forcing config.vm.box_version = "3.0" since I understand this is the latest version offically supported.

The error also appears if i force wpversion: "4.9.9".

**Comment by donkkis** [comment]
Was able to hack up a workaround.

Apparently, wp_dashboard_setup() is defined in wp-admin/includes/dashboard.php. For some reason, this file was empty after a clean install.

As a complete WP noob, I am starting to wonder whether it's an actual that the admin dashboard is not available out-of-the box or did something go wrong with my installation after all?

Re-cloning dashboard.php from WordPress resolves the issue, but clearly this is a suboptimal solution.

Further environment information:
Windows 7
VirtualBox 5.2.22
Vagrant 2.2.2
PowerShell 5.1 (perhaps not relevant, but what the heck)

**Comment by donkkis** [comment]
I obtained yet additional debugging information. Adding `wp core verify-checksums` to `wpdistillery.sh` right after the `wp core download` row gives:

    default: ========== WPDISTILLERY START ==========
    default: »»» creating root dir "public"...
    default: [=== INSTALL WORDPRESS ===]
    default: »»» downloading WordPress...
    default: Downloading WordPress 5.0 (fi)...
    default: md5 hash verified: 0a1bf31ea95bf1a9bacc0be38f1a28ac
    default: Success: WordPress downloaded.
    default: Warning: File doesn't verify against checksum: wp-login.php
    default: Warning: File doesn't verify against checksum: wp-admin/includes/meta-boxes.php
    default: Warning: File doesn't verify against checksum: wp-admin/includes/dashboard.php
    default: Warning: File doesn't verify against checksum: wp-admin/user-edit.php
    default: Warning: File doesn't verify against checksum: wp-includes/class-wp-customize-manager.php
    default: Error: WordPress installation doesn't verify against checksums.
    default: »»» aborting WPDistillery setup!
    default: bash: line 5: xit: command not found
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by flurinduerst** [comment]
what theme did you install on your installation?

**Comment by flurinduerst** [comment]
Hey donkkis

Did you try using a different locale or WP-version? Just to be able to rule out that the release you're using is broken.

This problem might be specific to the file you're trying to download. Please try the current WordPress-version and let us know if the issue still exists using WordPress 5.1.1

Are you using a windows-machine? Or to be more specific: are you using the `vagrant-winnfsd` plugin? It adds support for NFS on Windows and sometimes causes problems similar to what you're describing
