### ISSUE TITLE
Guest Additions required but not installed

### ISSUE THREAD

**Issue by bluehaoran** [flurinduerst/WPDistillery#93]
Hi there!

Love your work, but I ran into issues when doing a straight: 1) clone, 2) `vagrant up`.

This message:
> Vagrant was unable to mount VirtualBox shared folders. This is usually
> because the filesystem "vboxsf" is not available. This filesystem is
> made available via the VirtualBox Guest Additions and kernel module.
> Please verify that these guest additions are properly installed in the
> guest.

Running on:
* Vagrant 2.2.2
* VirtualBox 5.2.20.

**Comment by bluehaoran** [comment]
I was able to get a partial workaround using a certain snippet to force install VG Guest Additions. I am not sure if this is the best workaround, but I added to the top of the Vagrantfile.

```
REQUIRED_PLUGINS = %w(vagrant-vbguest)

# Ensure Vagrant vb-guest is installed
plugins_to_install = REQUIRED_PLUGINS.select { |plugin| not Vagrant.has_plugin? plugin }
if not plugins_to_install.empty?
  puts "Installing required plugins: #{plugins_to_install.join(' ')}"
  if system "vagrant plugin install #{plugins_to_install.join(' ')}"
    exec "vagrant #{ARGV.join(' ')}"
  else
    abort "Installation of one or more plugins has failed. Aborting. Please read the Bike Index README."
  end
end

```

**Comment by bluehaoran** [comment]
I bit of extra data on this: I believe that Scotchbox pre-supposes guest additions for VirtualBox 5.1, and something was incompatible with Virtualbox 5.2. But the code snippet above forces installation of the correct version.

**Comment by dutchigor** [comment]
I get the same issue. The above snippet did not solve the problem for me.

**Comment by flurinduerst** [comment]
Hey, sorry for being late to the party. This is a scotchbox related issue. Anyhow, the solution to this is to install vagrant-vbguest before running vagrant. This will install the correct vbguest package into the box.

```
vagrant plugin install vagrant-vbguest
vagrant vbguest
```

For details, please see https://github.com/scotch-io/scotch-box/issues/296

Please let me know if that solved your problem.

**Comment by dutchigor** [comment]
Thanks! that did the job for me.

**Comment by flurinduerst** [comment]
Added a note to the readme. See https://github.com/flurinduerst/WPDistillery/commit/e1d081fd3196545837858d6dbf7551109933200a
