### ISSUE TITLE
Public URLs

### ISSUE THREAD

**Issue by smth** [flurinduerst/WPDistillery#95]
Does WPDistillery have a way of facilitating pubic URLs, so they can be accessed by other devices on the network?

Otherwise, is there a recommended technique for this? I'm guessing the [manual ngrok setup](https://ngrok.com/docs#wordpress)?

**Comment by flurinduerst** [comment]
this is related to ScotchBox, not WPDistillery. Please see https://github.com/scotch-io/scotch-box
