### ISSUE TITLE
WPDistillery Script Aborts towards end

### ISSUE THREAD

**Issue by kranai** [flurinduerst/WPDistillery#99]
Hi

I had problem initially to install WP using WPDistillery and this was due to the setting in the php.ini file where I needed to set short_open_tag to "On" and also giving the right permission this file.

After correcting the above setting my next problem was that I was not able to install the WPSeed theme and also I don't see the previous themes being deleted as shown in the congfig.yml file. After investigating I found that there was a typo mistake in the config.yml the word theme was spelled without the 's'. After inserting the 's' in themes in the config.yml and I reloaded with provision.

During the installation all got installed nicely even the WPSeed and also removed the previous themes then once I again it aborted with the following message "Failed deleting  comment 1 (see image attached).

I tried to view the home page from my browser 192.168.33.10 and all I see is a warning message such as below: (see attached )
Warning: file_get_contents(http://192.168.33.10/wp-content/themes/WPSeed/dist/rev-manifest.json): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in /var/www/public/wp-content/themes/WPSeed/functions/functions-settings.php on line 165

I tried to find this file /wp-content/themes/WpSeed/dist/rev-manifest.json I cannot find the directory dist in WPSeed?

I am almost there I need to sort this tail end error and I think I should be able to see the home page at 192.168.33.10.

Please advise what I need to get resolve this error.

Best Rgds
![Capture-2](https://user-images.githubusercontent.com/56824977/69445616-a8b1dd00-0d8d-11ea-981d-43761e47d51c.JPG)
![Capture-3](https://user-images.githubusercontent.com/56824977/69445626-ac456400-0d8d-11ea-9451-b4dbc05cdbfb.JPG)

**Comment by scherii** [comment]
>I tried to find this file /wp-content/themes/WpSeed/dist/rev-manifest.json I cannot find the directory dist in WPSeed?

Maybe this leads you to the right path:
https://github.com/flurinduerst/WPSeed/blob/master/README.md#-installation

Running `gulp` creates the `dist` directory.

**Comment by flurinduerst** [comment]
Hi Kranai. 

There doesn't need to be any occurance of `themes` (with an "s") in config.yml. `theme` is correctly passed to wpdistillery.sh and executed in `wp theme install`, `wp theme activate $CONF_theme_rename` and other wpml commands.

The error "Failed deleting comment 1" probably means that there is no "comment 1" -> probably because you've ran the setup twice in a row, so the comments already got deleted. Try setting cleanup_comment to `false` on line 105 @ `config.yml`

The file `rev-manifest.json` is there to get the current stylesheet for cachebusting in WPSeed and is created by running gulp as @scherii stated. See https://github.com/flurinduerst/WPSeed/blob/master/README.md#general

**Comment by kranai** [comment]
Hi Guys

Thanks for the responses.

Okay I removed the 's' from themes and set the clean_comment to false on line 105 @ config.yml and did vagrant reload --provision.....outcome still the same it gave the same error as shown in the attached image.

Then I went to my browser to see the first page 192.168.33.10 and as expected the error was still there that I reported earlier. So I did what @scherii suggested and the following was my steps:

1. cd to the wp-content/themes directory
2. I did a mv WPSeed to WPSeed-old (it will not start the clone as it complains directory exist)
3. did the clone $ git clone git@github.com:flurinduerst/WPSeed.git and hit an error on permission as shown in the attached 

So I finally gave up...already spent too much time on this just to get WPSeed up and running correctly. I decided to set "theme: false" and will use the default page and then use another theme that I can download and install.

By the way I have asked someone who also tried to get WPSeed working and he too said he abandoned the idea as he hit problems as well. The problem is that you have a lot information all over the place and don't show exactly step by step how to get WPSeed installed via your WPDistillery.

I strongly urged you to create a video on how to successfully install the WPDistllery with WPSeed with AUDIO. The one you have on the website fall short to the tail end on what one suppose to see eventually on the screen. In addition to resolve all the other issue(s) it had with regard to the short_open_tag settings etc.

Until then I am not touching WPSeed or someone post a clear step-by-step instructions. Thanks for all the help in between. Much appreciated.

Best Rgds
Kish

![Capture-99](https://user-images.githubusercontent.com/56824977/69633489-460d5980-108b-11ea-9435-d93ac41a7f26.JPG)


![Capture-100](https://user-images.githubusercontent.com/56824977/69633498-4c9bd100-108b-11ea-91b8-25ce608c90d9.JPG)

**Comment by flurinduerst** [comment]
Thanks for your feedback Kish.

First of all, WPSeed is only the default setting in the configuration. As described in the readme, you can use any theme you want. WPSeed is completely independent from the WPDistillery.

WPSeed is very easy to install. If short_open_tag is set to on, nothing more needs to be done except to execute two commands: `npm install` and `gulp`. I don't think we need a video with audio for that, do we? By the way, short open tag is a setting, not an issue. 

I invest a lot of time and energy in this project and I'm happy to create more detailed tutorials if the community shows that it's worth something to them, e.g. with donations. In the last 3 years I've released 10 versions over 160 commits and haven't received a single cent for it. And that's totally fine, I don't do it for money, but when people tell me what kind of video tutorial to do, something went wrong. Normally I take orders from people who pay me. Ideas, suggestions or feedback, I gladly accept from everyone in this community.

**Comment by flurinduerst** [comment]
🎤👋🏻
